version: "3.7"

services:
  mongo:
    image: mongo:3.6
    container_name: clean-node-mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: clean-node-api
    image: node:12
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./:/usr/src/clean-node-api/
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo